---

- name: copy replica js file
  template:
    src: initialize-replica.js.j2
    dest: /tmp/initialize-replica.js

- block:
  - name: initilize replica set
    command: "mongo --port {{ port }} /tmp/initialize-replica.js"

  delegate_to: "{{ groups.all[0] }}"
  run_once: true